=== shining-yang/ripple-lib/src/api/common/schemas/ledger-closed.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "ledgerClosed",
  "description": "A ledgerClosed event message",
  "type": "object",
  "properties": {
    "feeBase": {"type": "integer", "minimum": 0},
    "feeReference": {"type": "integer", "minimum": 0},
    "ledgerHash": {"$ref": "ledgerHash"},
    "ledgerVersion": {"$ref": "ledgerVersion"},
    "ledgerTimestamp": {"type": "string", "format": "date-time"},
    "reserveBase": {"type": "integer", "minimum": 0},
    "reserveIncrement": {"type": "integer", "minimum": 0},
    "transactionCount": {"type": "integer", "minimum": 0},
    "validatedLedgerVersions": {"type": "string"}
  },
  "addtionalProperties": false,
  "required": ["feeBase", "feeReference", "ledgerHash", "ledgerTimestamp",
    "reserveBase", "reserveIncrement", "transactionCount",
    "ledgerVersion", "validatedLedgerVersions"]
}

=== shining-yang/ripple-lib/test/fixtures/api/responses/ledger-closed.json
{
  "feeBase": 10,
  "feeReference": 10,
  "ledgerVersion": 14804627,
  "ledgerHash": "9141FA171F2C0CE63E609466AF728FF66C12F7ACD4B4B50B0947A7F3409D593A",
  "ledgerTimestamp": "2015-07-23T05:50:40.000Z",
  "reserveBase": 20000000,
  "reserveIncrement": 5000000,
  "transactionCount": 19,
  "validatedLedgerVersions": "13983423-14804627"
}
